name: 'Clover Code Coverage Summary'
author: 'Sascha Nowak'
description: 'A GitHub Action to generate a code coverage summary from Clover XML reports.'
branding:
  icon: trending-up
  color: black
inputs:
  filename:
    description: 'Path and filename of the cobertura coverage report'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
